typo(05/636:37,117): 修正错别字和语义问题
transky-book/transky pull request #117
Opened 2024-08-02 02:33 UTC by iuu6

2024-08-02 02:34 UTC, Cryolitia submitted a review, later dismissed

2024-08-02 03:04 UTC, Zh40Le1ZOOB requested changes

2024-08-02 03:04 UTC, Zh40Le1ZOOB commented on src/08/004.md
> -林夕晨几乎全是被苏雨晴拉扯着狂奔，她自己没有什么动作，只是那眼神，开始变得逐渐冰冷。
个人认为这里没有问题

Cc @epifirumu

2024-08-03 10:00 UTC, epifirumu commented on src/08/004.md
> -林夕晨几乎全是被苏雨晴拉扯着狂奔，她自己没有什么动作，只是那眼神，开始变得逐渐冰冷。
原文这里不属于语义问题，修改可能造成原文含义变动：

个人觉得“全是”更倾向于直接强调在奔跑中的林夕晨的这种状态，“全靠”则更侧重于强调苏雨晴，表明林夕晨在“眼神冰冷”、“毫无动作”这样大脑一片空白的情况下能够逃离危险完全依赖于苏雨晴的帮助。

两种表达方式各有优缺点。但我们的README.md指出本项目旨在“在不改变内容含义与行文风格的前提下最大限度地修正错误”。
所以，我认为在没有明显问题的情况下应保留原文的表达方式。

2024-08-03 10:23 UTC, Zh40Le1ZOOB approved these changes

2024-08-03 10:25 UTC, Zh40Le1ZOOB commented
note: rebase and merge instead of suqash and merge

2024-08-03 10:32 UTC, epifirumu approved these changes
No issue detected✓

2024-08-03 12:42 UTC, merged